version: 0.0.1

phases:
  install:
    commands:
      # Install runtime dependencies
      - npm install --production

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
