export const FETCH_COEFFICIENTS = "Clients/FETCH_COEFFICIENTS";
export const FETCH_COEFFICIENTS_SUCCESS = "Clients/FETCH_COEFFICIENTS_SUCCESS";
export const FETCH_COEFFICIENTS_ERROR = "Clients/FETCH_COEFFICIENTS_ERROR";
