export const FETCH_CLIENTS = "Clients/FETCH_CLIENTS";
export const FETCH_CLIENTS_SUCCESS = "Clients/FETCH_CLIENTS_SUCCESS";
export const FETCH_CLIENTS_ERROR = "Clients/FETCH_CLIENTS_ERROR";

export const FETCH_REFERENCE_STATIONS = "Clients/FETCH_REFERENCE_STATIONS";
export const FETCH_REFERENCE_STATIONS_SUCCESS =
  "Clients/FETCH_REFERENCE_STATIONS_SUCCESS";
export const FETCH_REFERENCE_STATIONS_ERROR =
  "Clients/FETCH_REFERENCE_STATIONS_ERROR";

export const FETCH_LN_STATIONS = "Clients/FETCH_LN_STATIONS";
export const FETCH_LN_STATIONS_SUCCESS = "Clients/FETCH_LN_STATIONS_SUCCESS";
export const FETCH_LN_STATIONS_ERROR = "Clients/FETCH_LN_STATIONS_ERROR";

export const ADD_CLIENT = "Clients/ADD_CLIENT";
export const ADD_CLIENT_SUCCESS = "Clients/ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_ERROR = "Clients/ADD_CLIENT_ERROR";

export const EDIT_CLIENT = "Clients/EDIT_CLIENT";
export const EDIT_CLIENT_SUCCESS = "Clients/EDIT_CLIENT_SUCCESS";
export const EDIT_CLIENT_ERROR = "Clients/EDIT_CLIENT_ERROR";

export const EDIT_USER = "Clients/EDIT_USER";
export const EDIT_USER_SUCCESS = "Clients/EDIT_USER_SUCCESS";
export const EDIT_USER_ERROR = "Clients/EDIT_USER_ERROR";

export const DELETE_CLIENT = "Clients/DELETE_CLIENT";
export const DELETE_CLIENT_SUCCESS = "Clients/DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_ERROR = "Clients/DELETE_CLIENT_ERROR";

export const TOGGLE_CLIENT_MODAL = "Clients/TOGGLE_CLIENT_MODAL";
export const TOGGLE_USER_MODAL = "Clients/TOGGLE_USER_MODAL";

export const SET_CLIENT_DATA = "Clients/SET_CLIENT_DATA";
export const SET_CLIENT_ALERTS = "Clients/SET_CLIENT_ALERTS";

export const ADD_STATION = "Clients/ADD_STATION";
export const ADD_STATION_SUCCESS = "Clients/ADD_STATION_SUCCESS";
export const ADD_STATION_ERROR = "Clients/ADD_STATION_ERROR";

export const EDIT_STATION = "Clients/EDIT_STATION";
export const EDIT_STATION_SUCCESS = "Clients/EDIT_STATION_SUCCESS";
export const EDIT_STATION_ERROR = "Clients/EDIT_STATION_ERROR";

export const DELETE_STATION = "Clients/DELETE_STATION";
export const DELETE_STATION_SUCCESS = "Clients/DELETE_STATION_SUCCESS";
export const DELETE_STATION_ERROR = "Clients/DELETE_STATION_ERROR";

export const TOGGLE_STATION_MODAL = "Clients/TOGGLE_STATION_MODAL";

export const SET_STATION_DATA = "Clients/SET_STATION_DATA";

export const TOGGLE_IMPORT_MODAL = "Clients/TOGGLE_IMPORT_MODAL";
export const IMPORT_STATION_DATA = "Clients/IMPORT_STATION_DATA";
export const IMPORT_STATION_DATA_SUCCESS =
  "Clients/IMPORT_STATION_DATA_SUCCESS";
export const IMPORT_STATION_DATA_ERROR = "Clients/IMPORT_STATION_DATA_ERROR";

export const TOGGLE_ADJUST_COEFFICIENT_MODAL = "Clients/TOGGLE_ADJUST_COEFFICIENT_MODAL";
export const ADJUST_COEFFICIENT_STATION_DATA = "Clients/ADJUST_COEFFICIENT_STATION_DATA";
export const ADJUST_COEFFICIENT_STATION_DATA_SUCCESS =
  "Clients/ADJUST_COEFFICIENT_STATION_DATA_SUCCESS";
export const ADJUST_COEFFICIENT_STATION_DATA_ERROR = "Clients/ADJUST_COEFFICIENT_STATION_DATA_ERROR";
