export const SUCCESS = "App/SUCCESS";
export const WARNING = "App/WARNING";
export const ERROR = "App/ERROR";

export const RESET_ALERTS = "App/RESET_ALERTS";

export const FETCH_STATION_DATA = "App/FETCH_STATION_DATA";
export const FETCH_STATION_DATA_SUCCESS = "App/FETCH_STATION_DATA_SUCCESS";
export const FETCH_STATION_DATA_ERROR = "App/FETCH_STATION_DATA_ERROR";

export const FETCH_IDF_DATA = "App/FETCH_IDF_DATA";
export const FETCH_IDF_DATA_SUCCESS = "App/FETCH_IDF_DATA_SUCCESS";
export const FETCH_IDF_DATA_ERROR = "App/FETCH_IDF_DATA_ERROR";
