export const FETCH_PRECIPITATION_DATA = 'Dashboard/FETCH_PRECIPITATION_DATA'
export const FETCH_PRECIPITATION_DATA_SUCCESS = 'Dashboard/FETCH_PRECIPITATION_DATA_SUCCESS'
export const FETCH_PRECIPITATION_DATA_ERROR = 'Dashboard/FETCH_PRECIPITATION_DATA_ERROR'

export const INCREMENT_DAY = 'Dashboard/INCREMENT_DAY'
export const DECREMENT_DAY = 'Dashboard/DECREMENT_DAY'